version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - database
    container_name: todo-app-web
    environment:
      - TZ=Asia/Shanghai
      - DB_PORT=3306
      - DB_HOST=database

  database:
    container_name: todo-app-db
    image: postgres:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
